### ISSUE TITLE
Display does not fit screen

### ISSUE THREAD

**Issue by pyobox** [Swap-File/fbcp-ili9341#1]
I have fbcp-ili9341 running successfully for the most part, I got rid of the statisitic data and I have the screen orientated correctly, however, I can't get the display to fit the screen. Any ideas?
This what I get when I run it:
`bcm_host_get_peripheral_address:
0xfe000000, bcm_host_get_peripheral_size: 25165824, bcm_host_get_sdram_address: 0xc0000000 BCM core speed: current: 333333333hz, max turbo: 500000000hz. SPI CDIV: 30, SPI max frequency: 16666667hz Allocated DMA channel 7 Allocated DMA channel 1 Enabling DMA channels Tx:7 and Rx:1 DMA hardware register file is at ptr: 0xb532d000, using DMA TX channel: 7 and DMA RX channel: 1 DMA hardware TX channel register file is at ptr: 0xb532d700, DMA RX channel register file is at ptr: 0xb532d100 Resetting DMA channels for use DMA all set up Initializing display Resetting display at reset GPIO pin 24 Creating SPI task thread InitSPI done DISPLAY_FLIP_ORIENTATION_IN_SOFTWARE: Swapping width/height to update display in portrait mode to minimize tearing. Relevant source display area size with overscan cropped away: 768x1360. Source GPU display is 768x1360. Output SPI display is 240x240 with a drawable area of 240x240. Applying scaling factor horiz=0.18x & vert=0.18x, xOffset: 52, yOffset: 0, scaledWidth: 136, scaledHeight: 240 Creating dispmanX resource of size 136x240 (aspect ratio=0.566667). GPU grab rectangle is offset x=0,y=0, size w=136xh=240, aspect ratio=0.566667 All initialized, now running main loop...` 
![20201002_101445](https://user-images.githubusercontent.com/70666406/95389041-3d97c900-08c1-11eb-92b1-28121dbe6c98.jpg)

**Comment by Swap-File** [comment]
You may want to use the official version:

https://github.com/juj/fbcp-ili9341

My version was modified for an old project, and is likely very out of date.

**Comment by pyobox** [comment]
@Swap-File  i wrote #juj too but no response.  Im getting desperate

**Comment by Swap-File** [comment]
fbcp-ili9341 works by grabbing what would be displayed on HDMI, scaling it, and pushing it out the SPI port. If I had to guess, it might not like your HDMI output resolution of 768x1360.  Can you try other resolutions there?

**Comment by pyobox** [comment]
How do I do that, except switching monitors

**Comment by Swap-File** [comment]
Try defining something in /boot/config.txt ?  

with  tvservice -m CEA and  tvservice -m DMT you should be able to find out what your monitor supports.  Or just try defining something totally different and see if it works.

**Comment by pyobox** [comment]
I got it fixed by changing the value 320 to 280 in line 95 in the file st7735r.cpp:
      SPI_TRANSFER(0x37/*VSCSAD: Vertical Scroll Start Address of RAM*/, 0, 280 - DISPLAY_WIDTH);
